create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  reference text not null unique,
  customer_email text not null,
  amount numeric(10,2) not null,
  currency text not null default 'ZAR',
  status text not null default 'paid',
  payment_method text,
  card_brand text,
  card_last4 text,
  paid_at timestamptz not null,
  order_items jsonb not null default '[]'::jsonb,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;

create policy if not exists "Allow service role to manage orders"
  on public.orders
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');
